sonar.projectKey=L01-12345_snapify-frontend-v1
sonar.organization=l01-12345

# Đường dẫn tới thư mục code
sonar.sources=app,src

sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.exclusions=**/*.test.tsx, **/*.test.ts, node_modules/**
sonar.tests=__tests__