sonar.projectKey=L01-12345_snapify-frontend-v1
sonar.organization=l01-12345

# Đường dẫn tới code
# sonar.sources=app,src
# Loại trừ các file test khỏi việc phân tích lỗi logic
sonar.exclusions=**/*.test.tsx, **/*.test.ts, node_modules/**
sonar.inclusions=app/onboarding.tsx, app/(tabs)/dashboard.tsx
# Đường dẫn tới thư mục chứa code test
sonar.tests=__tests__

# Cực kỳ quan trọng để đẩy Coverage % lên Dashboard
sonar.javascript.lcov.reportPaths=coverage/lcov.infos