sonar.projectKey=L01-12345_snapify-frontend-v1
sonar.organization=l01-12345

# Đường dẫn tới thư mục code
sonar.sources=app,src

# CHÚ Ý 1: KHÔNG có khoảng trắng sau dấu phẩy
# sonar.inclusions=app/onboarding.tsx,app/(tabs)/dashboard.tsx

# CHÚ Ý 2: Dòng này CỰC KỲ QUAN TRỌNG để Sonar đọc được % Coverage
sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.exclusions=**/*.test.tsx, **/*.test.ts, node_modules/**
sonar.tests=__tests__